change script

diff --git a/0x12-web_stack_debugging_2/0-iamsomeoneelse b/0x12-web_stack_debugging_2/0-iamsomeoneelse
--- a/0x12-web_stack_debugging_2/0-iamsomeoneelse
+++ b/0x12-web_stack_debugging_2/0-iamsomeoneelse
@@ -1,15 +1,3 @@
 #!/usr/bin/env bash
 # Bash script that accepts one argument1
-if [ "$#" -eq 1 ]
-then
-    if id "$1" &>/dev/null; then
-        sudo -u "$1" whoami
-    else
-        sudo useradd "$1"
-        sudo -u "$1" whoami
-    fi
-fi
-if [ "$#" -eq 0 ]
-then
-    whoami
-fi
+sudo -u "$1" whoami || echo "There was an error";
